// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Sy4V9LIY95COfcXqRLx0mQE2WJgARNI',
    appId: '1:901933569621:web:793e44ef7952eb685d26dc',
    messagingSenderId: '901933569621',
    projectId: 'safehood-23a0d',
    authDomain: 'safehood-23a0d.firebaseapp.com',
    storageBucket: 'safehood-23a0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxf5QVWs3Bms5Qcl7FbZS9ZreiMScDGrY',
    appId: '1:901933569621:android:f3decd57cdec96ab5d26dc',
    messagingSenderId: '901933569621',
    projectId: 'safehood-23a0d',
    storageBucket: 'safehood-23a0d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDNPsqAaerRyBlRd1iV5m529QXoD129Ho',
    appId: '1:901933569621:ios:14f98b829e16b8ca5d26dc',
    messagingSenderId: '901933569621',
    projectId: 'safehood-23a0d',
    storageBucket: 'safehood-23a0d.firebasestorage.app',
    iosBundleId: 'com.example.safehood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDNPsqAaerRyBlRd1iV5m529QXoD129Ho',
    appId: '1:901933569621:ios:14f98b829e16b8ca5d26dc',
    messagingSenderId: '901933569621',
    projectId: 'safehood-23a0d',
    storageBucket: 'safehood-23a0d.firebasestorage.app',
    iosBundleId: 'com.example.safehood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Sy4V9LIY95COfcXqRLx0mQE2WJgARNI',
    appId: '1:901933569621:web:6cf72e805cbf02dd5d26dc',
    messagingSenderId: '901933569621',
    projectId: 'safehood-23a0d',
    authDomain: 'safehood-23a0d.firebaseapp.com',
    storageBucket: 'safehood-23a0d.firebasestorage.app',
  );
}
